# spring
spring:
  # HTML页面路径
  thymeleaf:
    prefix: classpath:/templates/
      # suffix: .html
  servlet:
    multipart:
      max-file-size: 1MB #文件大小
  # 自动注入mybatis-enhance-actable的Manager

  # redis 配置
  redis:
      host: 139.196.124.38 # Redis服务器IP
      port: 6379
      password: 123456
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      timeout: 20000 # 连接超时时间（毫秒）
      keyName:
                    exercise: exercises
  # 数据源配置
  datasource:
      url: jdbc:mysql://139.196.124.38:3306/scr?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false #139.196.124.38
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Mxd@123456
      type: com.alibaba.druid.pool.DruidDataSource
      #初始大小
      initialSize: 5
      #最大连接数
      maxActive: 30
      #最小连接数
      minIdle: 5
      #获取连接的最大等待时间
      maxWait: 10000
      #解决mysql8小时的问题
      validationgQuery: SELECT 'X'
      #空闲连接的检查时间间隔
      timeBetweenEvictionRunsMillis: 60000
      #空闲连接最小空闲时间
      minEvictableIdleTimeMillis: 300000
  # hot-deploy
  #  devtools:
  #    restart:
  #      enabled: true
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:xml/**/*.xml #若将**Mapper.xml文件放入静态文件目下的话，就需要更改mybatis.mapper-locations的路径(为xml文件的存放路径)。所以在自动生成类的时候就需要调整好各个类的结构，以便增加自定义SQL的时候，项目结构不会看起来很乱
  type-aliases-package: zzu.mxd.subway.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
# log
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} : %msg%n"
  level:
    com.wugengkj.springboot: debug
    org.springframework: info
    org.hibernate: info
server:
  port: 8084