/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class zzu_mxd_cpp_TestNative */

#ifndef _Included_zzu_mxd_cpp_TestNative
#define _Included_zzu_mxd_cpp_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zzu_mxd_cpp_TestNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zzu_mxd_cpp_TestNative_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
